import numpy as np
import pandas as pd

from kan_volatility.config import TRADING_DAYS_PER_YEAR

def compute_strategy_returns(
    asset_returns: pd.Series,
    weights: pd.Series,
    transaction_cost_bps: float = 1.0,
) -> pd.DataFrame:
    """
    Compute strategy returns from asset returns and portfolio weights.

    Important: 
    The weight at date t is shifted by one day before applying to returns.
    This avoids look-ahead bias.

    Parameters
    ----------
    asset_returns: Daily log or simple returns of the traded asset.
    weights: Target SPY weights generated by a model.
    transaction_cost_bps: Transaction cost in basis points per unit of turnover.

    Returns
    -------
    results: DataFrame with weights, turnover, costs, and strategy returns.
    """
    data = pd.DataFrame(
        {
            "asset_return": asset_returns,
            "target_weight": weights,
        }
    ).dropna()

    # Use yesterday's target weight for today's realized return.
    data["weight"] = data["target_weight"].shift(1)
    data["weight"] = data["weight"].fillna(0.0)

    data["turnover"] = data["target_weight"].diff().abs()
    data["turnover"] = data["turnover"].fillna(data["target_weight"].abs())

    transaction_cost = transaction_cost_bps / 10000
    data["transaction_cost"] = data["turnover"] * transaction_cost

    data["strategy_return_gross"] = data["weight"] * data["asset_return"]
    data["strategy_return"] = (
        data["strategy_return_gross"] - data["transaction_cost"]
    )

    data["benchmark_return"] = data["asset_return"]

    data["equity_curve"] = (1.0 + data["strategy_return"]).cumprod()
    data["benchmark_equity_curve"] = (1.0 + data["benchmark_return"]).cumprod()

    return data

def annualized_return(returns: pd.Series) -> float:
    """
    Compute annualized arithmetic compounded return.
    """
    returns = returns.dropna()

    if len(returns) == 0:
        return np.nan
    
    total_return = (1.0 + returns).prod()
    years = len(returns) / TRADING_DAYS_PER_YEAR

    if years <= 0:
        return np.nan
    
    return total_return ** (1.0 / years) - 1.0

def annualized_volatility(returns: pd.Series) -> float:
    """
    Compute annualized volatility.
    """
    returns = returns.dropna()

    if len(returns) == 0:
        return np.nan
    
    return returns.std() * np.sqrt(TRADING_DAYS_PER_YEAR)

def sharpe_ratio(
        returns: pd.Series,
        risk_free_rate: float = 0.0,
) -> float:
    """
    Compute annualized Sharpe ratio.

    For now, risk_free_rate is assumed to be annualized and constant.
    """
    returns = returns.dropna()

    if len(returns) == 0:
        return np.nan
    
    daily_rf = risk_free_rate / TRADING_DAYS_PER_YEAR
    excess_returns = returns - daily_rf

    vol = returns.std()

    if vol == 0 or np.isnan(vol):
        return np.nan
    
    return excess_returns.mean() / vol * np.sqrt(TRADING_DAYS_PER_YEAR)

def sortino_ratio(
    returns: pd.Series,
    risk_free_rate: float = 0.0,
) -> float:
    """
    Compute annualized Sortino ratio.
    """
    returns = returns.dropna()

    if len(returns) == 0:
        return np.nan
    
    daily_rf = risk_free_rate / TRADING_DAYS_PER_YEAR
    excess_returns = returns - daily_rf

    downside_returns = excess_returns[excess_returns < 0]

    downside_vol = downside_returns.std()

    if downside_vol == 0 or np.isnan(downside_vol):
        return np.nan
    
    return excess_returns.mean() / downside_vol * np.sqrt(TRADING_DAYS_PER_YEAR)

def max_drawdown(equity_curve: pd.Series) -> float:
    """
    Compute maximum drawdown from an equity curve.
    """
    equity_curve = equity_curve.dropna()

    if len(equity_curve) == 0:
        return np.nan
    
    running_max = equity_curve.cummax()
    drawdown = equity_curve / running_max - 1.0

    return drawdown.min()

def summarize_backtest(
    results: pd.DataFrame,
    strategy_name: str,
) -> dict[str, float | str]:
    """
    Summarize a backtest into common performance statistics.
    """
    strategy_returns = results["strategy_return"]
    benchmark_returns = results["benchmark_return"]

    return {
        "strategy": strategy_name,
        "start_date": results.index.min(),
        "end_date": results.index.max(),
        "total_return": results["equity_curve"].iloc[-1] - 1.0,
        "benchmark_total_return": results["benchmark_equity_curve"].iloc[-1] - 1.0,
        "annualized_return": annualized_return(strategy_returns),
        "benchmark_annualized_return": annualized_return(benchmark_returns),
        "annualized_volatility": annualized_volatility(strategy_returns),
        "benchmark_annualized_volatility": annualized_volatility(benchmark_returns),
        "sharpe": sharpe_ratio(strategy_returns),
        "benchmark_sharpe": sharpe_ratio(benchmark_returns),
        "sortino": sortino_ratio(strategy_returns),
        "benchmark_sortino": sortino_ratio(benchmark_returns),
        "max_drawdown": max_drawdown(results["equity_curve"]),
        "benchmark_max_drawdown": max_drawdown(results["benchmark_equity_curve"]),
        "average_weight": results["weight"].mean(),
        "average_turnover": results["turnover"].mean(),
        "total_turnover": results["turnover"].sum(),
    }
